# Generated by Django 2.2.12 on 2020-05-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='цена продукта'),
        ),
    ]
