# Generated by Django 2.2.12 on 2020-05-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_fill_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='Продуктов в наличии'),
        ),
    ]
